---
extends:
  - airbnb-standard
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  node: true
  jest: true
rules:
  no-underscore-dangle: 0
  no-template-curly-in-string: 0
  semi:
    - error
    - never
  max-len:
    - error
    - code: 200
plugins:
  - jest
